"""initial_schema

Revision ID: 9f60cf46a58a
Revises: 
Create Date: 2026-10-02 01:44:29.397042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f60cf46a58a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index('idx_workspaces_active', 'workspaces', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_workspaces_slug', 'workspaces', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_role', sa.Enum('owner', 'admin', 'member', 'guest', name='workspace_role_enum'), server_default='member', nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'suspended', 'deactivated', name='user_status_enum'), server_default='active', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_users_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_users_id_workspace')
    )
    op.create_index('idx_users_auth_lookup', 'users', ['workspace_id', 'auth_provider', 'auth_provider_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_workspace_role', 'users', ['workspace_id', 'workspace_role'], unique=False)
    op.create_index('idx_users_workspace_status', 'users', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_users_workspace_email', 'users', ['workspace_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_workspace_handle', 'users', ['workspace_id', 'handle'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_teams_creator', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_teams_lead', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_teams_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_teams_id_workspace')
    )
    op.create_index('idx_teams_workspace_lead', 'teams', ['workspace_id', 'lead_user_id'], unique=False)
    op.create_index('idx_teams_workspace_private', 'teams', ['workspace_id', 'is_private'], unique=False)
    op.create_index('uq_teams_workspace_slug', 'teams', ['workspace_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'paused', 'completed', 'archived', name='project_status_enum'), server_default='active', nullable=False),
    sa.Column('visibility', sa.Enum('workspace', 'private', name='project_visibility_enum'), server_default='workspace', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_projects_creator', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_projects_lead', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id', 'workspace_id'], ['teams.id', 'teams.workspace_id'], name='fk_projects_team', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_projects_id_workspace')
    )
    op.create_index('idx_projects_visibility', 'projects', ['workspace_id', 'visibility'], unique=False)
    op.create_index('idx_projects_workspace_lead', 'projects', ['workspace_id', 'lead_user_id'], unique=False)
    op.create_index('idx_projects_workspace_status', 'projects', ['workspace_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_projects_workspace_team', 'projects', ['workspace_id', 'team_id'], unique=False)
    op.create_index('uq_projects_workspace_slug', 'projects', ['workspace_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'member', 'contributor', name='team_role_enum'), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id', 'workspace_id'], ['teams.id', 'teams.workspace_id'], name='fk_team_members_team', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_team_members_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_team_members_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_pair')
    )
    op.create_index('idx_team_members_workspace_roster', 'team_members', ['workspace_id', 'team_id', 'role'], unique=False)
    op.create_index('idx_team_members_workspace_user', 'team_members', ['workspace_id', 'user_id'], unique=False)
    op.create_table('project_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('lead', 'maintainer', 'contributor', 'viewer', name='project_role_enum'), server_default='contributor', nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'revoked', name='invite_status_enum'), server_default='pending', nullable=False),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_project_invites_claimed_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_project_invites_inviter', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'workspace_id'], ['projects.id', 'projects.workspace_id'], name='fk_project_invites_project', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_project_invites_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_invites')),
    sa.UniqueConstraint('token_hash', name='uq_project_invites_token_hash')
    )
    op.create_index('idx_project_invites_status_expires', 'project_invites', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_project_invites_workspace', 'project_invites', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_project_invites_active', 'project_invites', ['project_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'maintainer', 'contributor', 'viewer', name='project_role_enum'), server_default='contributor', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'workspace_id'], ['projects.id', 'projects.workspace_id'], name='fk_project_members_project', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_project_members_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_project_members_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_pair')
    )
    op.create_index('idx_project_members_workspace_roster', 'project_members', ['workspace_id', 'project_id', 'role'], unique=False)
    op.create_index('idx_project_members_workspace_user', 'project_members', ['workspace_id', 'user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'todo', 'in_progress', 'in_review', 'done', 'cancelled', name='task_status_enum'), server_default='todo', nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'high', 'medium', 'low', 'none', name='task_priority_enum'), server_default='medium', nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_tasks_assignee', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_user_id', 'workspace_id'], ['users.id', 'users.workspace_id'], name='fk_tasks_creator', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_task_id', 'workspace_id'], ['tasks.id', 'tasks.workspace_id'], name='fk_tasks_parent', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id', 'workspace_id'], ['projects.id', 'projects.workspace_id'], name='fk_tasks_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tasks_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_tasks_id_workspace'),
    sa.UniqueConstraint('project_id', 'number', name='uq_tasks_project_number')
    )
    op.create_index('idx_tasks_due_calendar', 'tasks', ['workspace_id', 'due_date'], unique=False, postgresql_where=sa.text("due_date IS NOT NULL AND status NOT IN ('done', 'cancelled') AND deleted_at IS NULL"))
    op.create_index('idx_tasks_parent', 'tasks', ['parent_task_id'], unique=False, postgresql_where=sa.text('parent_task_id IS NOT NULL'))
    op.create_index('idx_tasks_workspace_assignee', 'tasks', ['workspace_id', 'assignee_user_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_tasks_workspace_creator', 'tasks', ['workspace_id', 'creator_user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_tasks_workspace_project_status', 'tasks', ['workspace_id', 'project_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_workspace_project_status', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_workspace_creator', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_workspace_assignee', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_parent', table_name='tasks', postgresql_where=sa.text('parent_task_id IS NOT NULL'))
    op.drop_index('idx_tasks_due_calendar', table_name='tasks', postgresql_where=sa.text("due_date IS NOT NULL AND status NOT IN ('done', 'cancelled') AND deleted_at IS NULL"))
    op.drop_table('tasks')
    op.drop_index('idx_project_members_workspace_user', table_name='project_members')
    op.drop_index('idx_project_members_workspace_roster', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('uq_project_invites_active', table_name='project_invites', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_project_invites_workspace', table_name='project_invites')
    op.drop_index('idx_project_invites_status_expires', table_name='project_invites', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('project_invites')
    op.drop_index('idx_team_members_workspace_user', table_name='team_members')
    op.drop_index('idx_team_members_workspace_roster', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('uq_projects_workspace_slug', table_name='projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_projects_workspace_team', table_name='projects')
    op.drop_index('idx_projects_workspace_status', table_name='projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_projects_workspace_lead', table_name='projects')
    op.drop_index('idx_projects_visibility', table_name='projects')
    op.drop_table('projects')
    op.drop_index('uq_teams_workspace_slug', table_name='teams', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_teams_workspace_private', table_name='teams')
    op.drop_index('idx_teams_workspace_lead', table_name='teams')
    op.drop_table('teams')
    op.drop_index('uq_users_workspace_handle', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_workspace_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_workspace_status', table_name='users')
    op.drop_index('idx_users_workspace_role', table_name='users')
    op.drop_index('idx_users_auth_lookup', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('uq_workspaces_slug', table_name='workspaces', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_workspaces_active', table_name='workspaces', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workspaces')

    # Drop PostgreSQL native ENUM types
    sa.Enum(name='task_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='invite_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='project_role_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='project_visibility_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='project_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='team_role_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workspace_role_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
